[k8s_masters]
master-01 ansible_host=CONTROL_PLANE_1
master-02 ansible_host=CONTROL_PLANE_2
master-03 ansible_host=CONTROL_PLANE_3

[k8s_workers]
worker-01 ansible_host=WORKER_1
worker-02 ansible_host=WORKER_2

[k8s_nodes:children]
k8s_masters
k8s_workers

[devops]
devops-tools ansible_host=DEVOPS_VM

[database]
postgres ansible_host=DB_VM

[edge_lb]
edge-lb ansible_host=EDGE_LB

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa